# Travis CI Configuration File

# Tell Travis CI we're using PHP
language: php

# Versions of PHP to test against
php:
    - "5.3"
    - "5.4"
    - "5.5"

# Specify versions of WordPress to test against
# WP_VERSION = WordPress version number (use "master" for SVN trunk)
# WP_MULTISITE = whether to test multisite (use either "0" or "1")
env:
    - WP_VERSION=master WP_MULTISITE=0
    - WP_VERSION=3.6 WP_MULTISITE=0
    - WP_VERSION=3.5.2 WP_MULTISITE=0
    - WP_VERSION=master WP_MULTISITE=1
    - WP_VERSION=3.6 WP_MULTISITE=1
    - WP_VERSION=3.5.2 WP_MULTISITE=1

before_script:
echo "extension = xdebug.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
- curl http://cs.sensiolabs.org/get/php-cs-fixer.phar -o php-cs-fixer.phar
- curl -s http://getcomposer.org/installer | php
- php composer.phar install --dev --no-interaction --prefer-source
#Coveralls support
- mkdir -p build/logs
- mkdir -p build/cov

- wget https://raw.github.com/tierra/wordpress-plugin-tests/setup/setup.sh
- source setup.sh

script: phpunit

after_script:
- php vendor/bin/coveralls -v --dry-run

# wordpress-plugin-tests specific config
# Tells Travis CI not to run unit tests against the setup branch
branches:
    except:
        - setup