script: phpunit
after_script: 
- php vendor/bin/coveralls -v
php: 
- "5.3"
- "5.4"
language: php
notifications: 
  hipchat: 
    rooms: 
      secure: VAdYhhXqaIdU+J4hca0fQydOHsWmtSbyupgOkvwT0akzslc5uGliodWkqkFuHCP+rGmeJIsoa/s9tj7YbmD7dlku7vva6d7KcX6W4jmHKlydBkEFzpO2N7w4ZGR501o428ZfLor/MVEKF/+FwRkMTT3RBDLNjcYOhFDGrvf2CyY=
branches: 
  except: 
  - setup
before_script: 
- echo "extension = xdebug.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
- curl http://cs.sensiolabs.org/get/php-cs-fixer.phar -o php-cs-fixer.phar
- curl -s http://getcomposer.org/installer | php
- php composer.phar install --dev --no-interaction --prefer-source
- mkdir -p build/logs
- mkdir -p build/cov
- wget https://raw.github.com/tierra/wordpress-plugin-tests/setup/setup.sh
- source setup.sh
env: 
- WP_VERSION=master WP_MULTISITE=0
- WP_VERSION=3.8.1 WP_MULTISITE=0
- WP_VERSION=3.8 WP_MULTISITE=0
- WP_VERSION=3.7 WP_MULTISITE=0
- WP_VERSION=master WP_MULTISITE=1
- WP_VERSION=3.8.1 WP_MULTISITE=1
- WP_VERSION=3.8 WP_MULTISITE=1
- WP_VERSION=3.7 WP_MULTISITE=1
